### ISSUE TITLE
TypeError: Cannot redefine property: AuthenticatedRoutesWrapper

### ISSUE THREAD

**Issue by Neewd** [ElrondNetwork/dapp-core-components#1]
I just created a new NextJS project with the new Dapp-core-components, imported the DappProvider from the Dapp-core-components, and I have this error.
![Capture d’écran 2022-01-21 à 09 45 02](https://user-images.githubusercontent.com/2735205/150495979-acf938cb-4781-4a14-b83d-e14aa5f6250f.png)

**Comment by noc2spam** [comment]
Got the same on our next.js setup as well.
